parameters:

    tesla_client.http_client_factory.class: Tesla\Bundle\ClientBundle\Client\HttpClientFactory
    tesla_client.http_proxy_factory.class: Tesla\Bundle\ClientBundle\Proxy\HttpProxyFactory
    tesla_client.http_client.class: Tesla\Bundle\ClientBundle\Client\HttpClient
    tesla_client.http_proxy.class: Tesla\Bundle\ClientBundle\Proxy\HttpProxy
    
services:


    tesla_client.memcache_driver:
         class: Memcache
         public: false
         calls:
             - [addServer, [localhost, 11211]]
         
    tesla_client.generic_cache:
         class: %doctrine.orm.cache.memcache.class%
         public: false
         calls:
             - [setNamespace, [%tesla_client.configuration.cache_namespace%]]
             - [setMemcache, [@tesla_client.memcache_driver]]
        

    tesla_client.http_client_factory:
        class: %tesla_client.http_client_factory.class%
        public: true
        arguments:
            - %tesla_client.configuration%
            - @tesla_client.generic_cache
            
    tesla_client.http_proxy_factory:
        class: %tesla_client.http_proxy_factory.class%
        public: true
        arguments:
            - %tesla_client.configuration%
            - @tesla_client.generic_cache
        calls:
            - [setOriginRequest, [@?request=]]
            
    tesla_client.http_client:
        class: %tesla_client.http_client.class%
        factory_service: tesla_client.http_client_factory
        factory_method: get
        
  